[package]
name = "url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
heed = "0.20.5"
rand = "0.8.5"
serde = "1.0.215"
sha3 = "0.10.8"
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
